PROFILE_KZ8A = {
    "id": "KZ8A",
    "name": "KZ8A",
    "type": "electric",
    "resource_type": "energy",
    "resource_unit": "percent",
    "fuel_max_liters": None,
    "max_speed_kmh": 140,
    "description": "Магистральный электровоз KZ8A",
    "params": {
        "speed_kmh": {
            "label": "Скорость",
            "unit": "км/ч",
            "direction": "high",
            "norm": [0, 120],
            "warning": [121, 139],
            "critical": [140, 999],
            "penalty_warn": 7,
            "penalty_crit": 20,
            "alert_code": "E006",
            "alert_msg": "Превышение скорости",
            "recommend_warn": "Снизьте скорость до рабочего диапазона.",
            "recommend_crit": "⛔ Немедленно снизьте скорость.",
        },
        "engine_temp_c": {
            "label": "Температура силового оборудования",
            "unit": "°C",
            "direction": "high",
            "norm": [40, 85],
            "warning": [85, 95],
            "critical": [95, 999],
            "penalty_warn": 8,
            "penalty_crit": 20,
            "alert_code": "E001",
            "alert_msg": "Перегрев силового оборудования",
            "recommend_warn": "Снизьте нагрузку и контролируйте температуру.",
            "recommend_crit": "⚠️ Немедленно снизьте тягу и сообщите диспетчеру.",
        },
        "oil_temp_c": {
            "label": "Температура масла",
            "unit": "°C",
            "direction": "high",
            "norm": [40, 75],
            "warning": [75, 85],
            "critical": [85, 999],
            "penalty_warn": 6,
            "penalty_crit": 15,
            "alert_code": "E003",
            "alert_msg": "Перегрев масла",
            "recommend_warn": "Проверьте систему охлаждения.",
            "recommend_crit": "⚠️ Критический перегрев масла. Снизьте нагрузку.",
        },
        "brake_pressure_bar": {
            "label": "Давление тормозной магистрали",
            "unit": "бар",
            "direction": "low",
            "norm": [5.0, 9.0],
            "warning": [4.0, 4.9],
            "critical": [0.0, 3.9],
            "penalty_warn": 6,
            "penalty_crit": 15,
            "alert_code": "E007",
            "alert_msg": "Давление тормозной магистрали вне нормы",
            "recommend_warn": "Проверьте тормозную систему.",
            "recommend_crit": "⛔ Критическое давление тормозов! Нужна проверка.",
        },
        "compressor_bar": {
            "label": "Давление компрессора",
            "unit": "бар",
            "direction": "high",
            "norm": [6.0, 10.0],
            "warning": [10.0, 11.0],
            "critical": [11.0, 999],
            "penalty_warn": 4,
            "penalty_crit": 10,
            "alert_code": "E010",
            "alert_msg": "Давление компрессора превышено",
            "recommend_warn": "Проверьте клапан сброса давления.",
            "recommend_crit": "⛔ Критическое давление компрессора.",
        },
        "voltage_aux_v": {
            "label": "Напряжение вспомогательной сети",
            "unit": "В",
            "direction": "low",
            "norm": [80, 130],
            "warning": [70, 79],
            "critical": [0, 69],
            "penalty_warn": 6,
            "penalty_crit": 15,
            "alert_code": "E005",
            "alert_msg": "Низкое напряжение вспомогательной сети",
            "recommend_warn": "Проверьте резервное питание.",
            "recommend_crit": "⛔ Критическое напряжение. Немедленно переключитесь на резерв.",
        },
    },
    "alert_penalties": {
        "CRITICAL": 15,
        "WARNING": 8,
        "INFO": 3,
    },
    "health_categories": {
        "NORM": {"min": 80, "max": 100, "color": "#4CAF50", "label": "Норма"},
        "WARNING": {"min": 60, "max": 79, "color": "#FF9800", "label": "Внимание"},
        "CRITICAL": {"min": 0, "max": 59, "color": "#F44336", "label": "Критично"},
    },
    "initial_state": {
        "speed_kmh": 85.0,
        "engine_temp_c": 70.0,
        "oil_temp_c": 62.0,
        "brake_pressure_bar": 6.4,
        "compressor_bar": 8.6,
        "voltage_aux_v": 98.0,
        "alerts": [],
    },
}