PROFILE_TE33A = {
    "id": "TE33A",
    "name": "ТЭ33А",
    "type": "diesel",
    "resource_type": "fuel",
    "resource_unit": "liters",
    "fuel_max_liters": 8000,
    "max_speed_kmh": 120,
    "description": "Грузовой магистральный тепловоз GE Evolution ES44ACi",
    "params": {
        "speed_kmh": {
            "label": "Скорость",
            "unit": "км/ч",
            "direction": "high",
            "norm": [0, 110],
            "warning": [111, 119],
            "critical": [120, 999],
            "penalty_warn": 7,
            "penalty_crit": 20,
            "alert_code": "F006",
            "alert_msg": "Превышение скорости",
            "recommend_warn": "Снизьте скорость. Превышение допустимого предела.",
            "recommend_crit": "⛔ НЕМЕДЛЕННО снизить скорость до 110 км/ч!",
        },
        "fuel_liters": {
            "label": "Топливо",
            "unit": "л",
            "direction": "low",
            "norm": [1000, 8000],
            "warning": [500, 999],
            "critical": [0, 499],
            "penalty_warn": 8,
            "penalty_crit": 20,
            "alert_code": "F004",
            "alert_msg": "Низкий уровень топлива",
            "recommend_warn": "Запланируйте дозаправку. Уточните ближайшую станцию у диспетчера.",
            "recommend_crit": "⛔ Срочная дозаправка. Топлива менее 500 литров!",
        },
        "rpm": {
            "label": "Обороты двигателя",
            "unit": "об/мин",
            "direction": "high",
            "norm": [800, 2000],
            "warning": [2000, 2100],
            "critical": [2100, 9999],
            "penalty_warn": 7,
            "penalty_crit": 20,
            "alert_code": "F008",
            "alert_msg": "Превышение оборотов двигателя",
            "recommend_warn": "Снизьте позицию контроллера.",
            "recommend_crit": "⛔ Критические обороты! Снизить нагрузку немедленно. Риск автостопа.",
        },
        "engine_temp_c": {
            "label": "Температура двигателя",
            "unit": "°C",
            "direction": "high",
            "norm": [60, 95],
            "warning": [95, 102],
            "critical": [102, 999],
            "penalty_warn": 8,
            "penalty_crit": 20,
            "alert_code": "F001",
            "alert_msg": "Перегрев двигателя",
            "recommend_warn": "Снизьте нагрузку. Следите за динамикой температуры.",
            "recommend_crit": "⚠️ НЕМЕДЛЕННО снизить скорость. Связаться с диспетчером. Возможна остановка.",
        },
        "exhaust_temp_c": {
            "label": "Температура выхлопа",
            "unit": "°C",
            "direction": "high",
            "norm": [200, 550],
            "warning": [550, 700],
            "critical": [700, 999],
            "penalty_warn": 6,
            "penalty_crit": 15,
            "alert_code": "F009",
            "alert_msg": "Высокая температура выхлопных газов",
            "recommend_warn": "Снизьте нагрузку двигателя. Проверьте систему EGR.",
            "recommend_crit": "⛔ Критическая температура выхлопа! Снизить тягу немедленно.",
        },
        "oil_temp_c": {
            "label": "Температура масла",
            "unit": "°C",
            "direction": "high",
            "norm": [60, 90],
            "warning": [90, 98],
            "critical": [98, 999],
            "penalty_warn": 6,
            "penalty_crit": 15,
            "alert_code": "F003",
            "alert_msg": "Перегрев масла",
            "recommend_warn": "Снизьте скорость. Проверьте систему охлаждения.",
            "recommend_crit": "⚠️ Перегрев масла критический! Снизить нагрузку.",
        },
        "oil_pressure_bar": {
            "label": "Давление масла",
            "unit": "бар",
            "direction": "low",
            "norm": [2.0, 7.0],
            "warning": [2.0, 3.4],
            "critical": [0.0, 2.0],
            "penalty_warn": 8,
            "penalty_crit": 20,
            "alert_code": "F002",
            "alert_msg": "Низкое давление масла",
            "recommend_warn": "Проверьте уровень масла на ближайшей остановке.",
            "recommend_crit": "⛔ СТОП. Критическое давление масла. Риск повреждения двигателя!",
        },
        "brake_pressure_bar": {
            "label": "Давление тормозной магистрали",
            "unit": "бар",
            "direction": "low",
            "norm": [5.0, 9.0],
            "warning": [4.0, 4.9],
            "critical": [0.0, 3.9],
            "penalty_warn": 6,
            "penalty_crit": 15,
            "alert_code": "F007",
            "alert_msg": "Давление тормозной магистрали вне нормы",
            "recommend_warn": "Проверьте тормозную систему.",
            "recommend_crit": "⛔ Критическое давление тормозов! Немедленная проверка.",
        },
        "compressor_bar": {
            "label": "Давление компрессора",
            "unit": "бар",
            "direction": "high",
            "norm": [6.0, 10.0],
            "warning": [10.0, 11.0],
            "critical": [11.0, 999],
            "penalty_warn": 4,
            "penalty_crit": 10,
            "alert_code": "F010",
            "alert_msg": "Давление компрессора превышено",
            "recommend_warn": "Проверьте клапан сброса давления.",
            "recommend_crit": "⛔ Давление компрессора критическое! Автосброс должен сработать.",
        },
        "voltage_aux_v": {
            "label": "Напряжение бортовой сети",
            "unit": "В",
            "direction": "low",
            "norm": [72, 120],
            "warning": [60, 71],
            "critical": [0, 59],
            "penalty_warn": 6,
            "penalty_crit": 15,
            "alert_code": "F005",
            "alert_msg": "Низкое напряжение бортовой сети",
            "recommend_warn": "Проверьте аккумуляторы. Переключить на резерв.",
            "recommend_crit": "⛔ Критическое напряжение! Включить резервное питание.",
        },
    },
    "alert_penalties": {
        "CRITICAL": 15,
        "WARNING": 8,
        "INFO": 3,
    },
    "health_categories": {
        "NORM": {"min": 80, "max": 100, "color": "#4CAF50", "label": "Норма"},
        "WARNING": {"min": 60, "max": 79, "color": "#FF9800", "label": "Внимание"},
        "CRITICAL": {"min": 0, "max": 59, "color": "#F44336", "label": "Критично"},
    },
    "initial_state": {
        "speed_kmh": 75.0,
        "fuel_liters": 6000.0,
        "rpm": 1800,
        "engine_temp_c": 88.0,
        "exhaust_temp_c": 420.0,
        "oil_temp_c": 80.0,
        "oil_pressure_bar": 4.8,
        "brake_pressure_bar": 6.5,
        "compressor_bar": 8.5,
        "voltage_aux_v": 96.0,
        "alerts": [],
    },
}